# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Elternrat Lenzburg
email: info@elternratlenzburg.ch
description: "Gemeinsam unterwegs zum Wohle unserer Kinder"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.elternratlenzburg.ch" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal

# a dynamic calendar for a static site inspired by
# https://www.raymondcamden.com/2017/02/24/an-example-of-a-static-site-with-a-dynamic-calendar/
collections:
  events:
    output: true
    permalink: /events/:path/
    title: Events
